// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ULGdWrlzxxqb_H45sgQQwCkzeysvf7E',
    appId: '1:475834097247:web:5876900f1f3a65c4fe85ea',
    messagingSenderId: '475834097247',
    projectId: 'inclassact13',
    authDomain: 'inclassact13.firebaseapp.com',
    storageBucket: 'inclassact13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7cSjaJqtUCMJOft-gD-c1sHCv9UdAsiM',
    appId: '1:475834097247:android:31495d2a2734603afe85ea',
    messagingSenderId: '475834097247',
    projectId: 'inclassact13',
    storageBucket: 'inclassact13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnF4WIStK0GdAmIDvisXUG-xMnKxtpF3E',
    appId: '1:475834097247:ios:7f39469ee65fd33cfe85ea',
    messagingSenderId: '475834097247',
    projectId: 'inclassact13',
    storageBucket: 'inclassact13.firebasestorage.app',
    iosBundleId: 'com.example.inclassact13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnF4WIStK0GdAmIDvisXUG-xMnKxtpF3E',
    appId: '1:475834097247:ios:7f39469ee65fd33cfe85ea',
    messagingSenderId: '475834097247',
    projectId: 'inclassact13',
    storageBucket: 'inclassact13.firebasestorage.app',
    iosBundleId: 'com.example.inclassact13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ULGdWrlzxxqb_H45sgQQwCkzeysvf7E',
    appId: '1:475834097247:web:96506d202ee7557cfe85ea',
    messagingSenderId: '475834097247',
    projectId: 'inclassact13',
    authDomain: 'inclassact13.firebaseapp.com',
    storageBucket: 'inclassact13.firebasestorage.app',
  );
}
